// Mock jobs data pulled 

export const postedJobs = [
    {
      id: 1,
      title: "Frontend Developer",
      description: "We are looking for a Frontend Developer to join our team.",
      requirements: "Proficiency in JavaScript, React, and CSS.",
      tags: ["JavaScript", "React", "CSS"],
      companyName: "Tech Innovations",
      contactInfo: "hr@techinnovations.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-01",
      applications: [
        { id: 1, name: "Alice", email: "alice@example.com" },
        { id: 2, name: "Bob", email: "bob@example.com" },
        { id: 3, name: "Charlie", email: "charlie@example.com" },
        { id: 4, name: "David", email: "david@example.com" },
        { id: 5, name: "Emma", email: "emma@example.com" },
      ],
    },
    {
      id: 2,
      title: "Backend Developer",
      description: "Seeking a skilled Backend Developer for our services.",
      requirements: "Experience with Node.js and databases.",
      tags: ["Node.js", "Express", "MongoDB"],
      companyName: "Innovatech",
      contactInfo: "hr@innovatech.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-02",
      applications: [
        { id: 6, name: "Frank", email: "frank@example.com" },
        { id: 7, name: "Grace", email: "grace@example.com" },
        { id: 8, name: "Hank", email: "hank@example.com" },
        { id: 9, name: "Ivy", email: "ivy@example.com" },
        { id: 10, name: "Jack", email: "jack@example.com" },
      ],
    },
    {
      id: 3,
      title: "UI/UX Designer",
      description: "Looking for a creative UI/UX Designer.",
      requirements: "Experience in Figma and Adobe Suite.",
      tags: ["UI", "UX", "Figma"],
      companyName: "Design Studio",
      contactInfo: "info@designstudio.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-03",
      applications: [
        { id: 11, name: "Kathy", email: "kathy@example.com" },
        { id: 12, name: "Leo", email: "leo@example.com" },
        { id: 13, name: "Mia", email: "mia@example.com" },
        { id: 14, name: "Nina", email: "nina@example.com" },
      ],
    },
    {
      id: 4,
      title: "Data Scientist",
      description: "Join us as a Data Scientist.",
      requirements: "Experience with Python and machine learning.",
      tags: ["Python", "Machine Learning", "Data Analysis"],
      companyName: "Data Insights",
      contactInfo: "contact@datainsights.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-04",
      applications: [
        { id: 15, name: "Owen", email: "owen@example.com" },
        { id: 16, name: "Pam", email: "pam@example.com" },
        { id: 17, name: "Quinn", email: "quinn@example.com" },
        { id: 18, name: "Rita", email: "rita@example.com" },
        { id: 19, name: "Sam", email: "sam@example.com" },
        { id: 20, name: "Tina", email: "tina@example.com" },
      ],
    },
    {
      id: 5,
      title: "DevOps Engineer",
      description: "Seeking a DevOps Engineer for cloud solutions.",
      requirements: "Experience with AWS and CI/CD.",
      tags: ["AWS", "DevOps", "CI/CD"],
      companyName: "Cloud Solutions",
      contactInfo: "info@cloudsolutions.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-05",
      applications: [
        { id: 21, name: "Uma", email: "uma@example.com" },
        { id: 22, name: "Vera", email: "vera@example.com" },
        { id: 23, name: "Will", email: "will@example.com" },
      ],
    },
    {
      id: 6,
      title: "Product Manager",
      description: "Looking for a Product Manager to lead our team.",
      requirements: "Experience in product lifecycle management.",
      tags: ["Product Management", "Agile", "Scrum"],
      companyName: "Tech Giants",
      contactInfo: "hr@techgiants.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-06",
      applications: [
        { id: 24, name: "Xena", email: "xena@example.com" },
        { id: 25, name: "Yara", email: "yara@example.com" },
        { id: 26, name: "Zane", email: "zane@example.com" },
      ],
    },
    {
      id: 7,
      title: "Mobile App Developer",
      description: "Seeking a Mobile App Developer for iOS and Android.",
      requirements: "Experience with Flutter and React Native.",
      tags: ["Flutter", "React Native", "Mobile"],
      companyName: "App Masters",
      contactInfo: "info@appmasters.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-07",
      applications: [
        { id: 27, name: "Alice", email: "alice@example.com" },
        { id: 28, name: "Bob", email: "bob@example.com" },
        { id: 29, name: "Charlie", email: "charlie@example.com" },
        { id: 30, name: "David", email: "david@example.com" },
      ],
    },
    {
      id: 8,
      title: "Content Writer",
      description: "Looking for a skilled Content Writer.",
      requirements: "Experience in SEO and blog writing.",
      tags: ["Content Writing", "SEO", "Blogging"],
      companyName: "Content Hub",
      contactInfo: "hr@contenthub.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-08",
      applications: [
        { id: 31, name: "Emma", email: "emma@example.com" },
        { id: 32, name: "Frank", email: "frank@example.com" },
        { id: 33, name: "Grace", email: "grace@example.com" },
      ],
    },
    {
      id: 9,
      title: "System Administrator",
      description: "Join us as a System Administrator.",
      requirements: "Experience with Windows and Linux servers.",
      tags: ["SysAdmin", "Windows", "Linux"],
      companyName: "Tech Solutions",
      contactInfo: "info@techsolutions.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-09",
      applications: [
        { id: 34, name: "Hank", email: "hank@example.com" },
        { id: 35, name: "Ivy", email: "ivy@example.com" },
      ],
    },
    {
      id: 10,
      title: "Network Engineer",
      description: "Looking for a Network Engineer to manage our network.",
      requirements: "Experience with Cisco and network security.",
      tags: ["Network Engineering", "Cisco", "Security"],
      companyName: "Network Pros",
      contactInfo: "hr@networkpros.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-10",
      applications: [
        { id: 36, name: "Jack", email: "jack@example.com" },
        { id: 37, name: "Kathy", email: "kathy@example.com" },
        { id: 38, name: "Leo", email: "leo@example.com" },
        { id: 39, name: "Mia", email: "mia@example.com" },
      ],
    },
    {
      id: 11,
      title: "Graphic Designer",
      description: "Seeking a talented Graphic Designer.",
      requirements: "Experience with Adobe Illustrator and Photoshop.",
      tags: ["Graphic Design", "Adobe", "Illustrator"],
      companyName: "Creative Agency",
      contactInfo: "contact@creativeagency.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-11",
      applications: [
        { id: 40, name: "Nina", email: "nina@example.com" },
        { id: 41, name: "Owen", email: "owen@example.com" },
      ],
    },
    {
      id: 12,
      title: "SEO Specialist",
      description: "Looking for an SEO Specialist to optimize our website.",
      requirements: "Experience with Google Analytics and SEO tools.",
      tags: ["SEO", "Google Analytics", "Marketing"],
      companyName: "Digital Marketing",
      contactInfo: "info@digitalmarketing.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-12",
      applications: [
        { id: 42, name: "Pam", email: "pam@example.com" },
        { id: 43, name: "Quinn", email: "quinn@example.com" },
        { id: 44, name: "Rita", email: "rita@example.com" },
      ],
    },
    {
      id: 13,
      title: "Business Analyst",
      description: "Join us as a Business Analyst.",
      requirements: "Experience in analyzing business needs.",
      tags: ["Business Analysis", "Requirements Gathering", "Documentation"],
      companyName: "Analytics Co",
      contactInfo: "hr@analyticsco.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-13",
      applications: [
        { id: 45, name: "Sam", email: "sam@example.com" },
        { id: 46, name: "Tina", email: "tina@example.com" },
      ],
    },
    {
      id: 14,
      title: "Marketing Manager",
      description: "Seeking a Marketing Manager to drive our campaigns.",
      requirements: "Experience with digital marketing strategies.",
      tags: ["Marketing", "Campaign Management", "Digital"],
      companyName: "Market Leaders",
      contactInfo: "info@marketleaders.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-14",
      applications: [
        { id: 47, name: "Uma", email: "uma@example.com" },
        { id: 48, name: "Vera", email: "vera@example.com" },
        { id: 49, name: "Will", email: "will@example.com" },
      ],
    },
    {
      id: 15,
      title: "Software Engineer",
      description: "Looking for a Software Engineer to develop applications.",
      requirements: "Experience with Java and Spring framework.",
      tags: ["Java", "Spring", "Software Development"],
      companyName: "Dev Innovations",
      contactInfo: "hr@devinnovations.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-15",
      applications: [
        { id: 50, name: "Xena", email: "xena@example.com" },
        { id: 51, name: "Yara", email: "yara@example.com" },
        { id: 52, name: "Zane", email: "zane@example.com" },
      ],
    },
    {
      id: 16,
      title: "Database Administrator",
      description: "Join us as a Database Administrator.",
      requirements: "Experience with SQL and database management.",
      tags: ["SQL", "Database Management", "DBA"],
      companyName: "Data Solutions",
      contactInfo: "info@datasolutions.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-16",
      applications: [
        { id: 53, name: "Alice", email: "alice@example.com" },
        { id: 54, name: "Bob", email: "bob@example.com" },
        { id: 55, name: "Charlie", email: "charlie@example.com" },
      ],
    },
    {
      id: 17,
      title: "Web Developer",
      description: "Seeking a Web Developer for our projects.",
      requirements: "Proficiency in HTML, CSS, and JavaScript.",
      tags: ["HTML", "CSS", "JavaScript"],
      companyName: "Web Creators",
      contactInfo: "hr@webcreators.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-17",
      applications: [
        { id: 56, name: "David", email: "david@example.com" },
        { id: 57, name: "Emma", email: "emma@example.com" },
        { id: 58, name: "Frank", email: "frank@example.com" },
        { id: 59, name: "Grace", email: "grace@example.com" },
      ],
    },
    {
      id: 18,
      title: "Mobile UI Designer",
      description: "Looking for a Mobile UI Designer for app interfaces.",
      requirements: "Experience with mobile design principles.",
      tags: ["Mobile Design", "UI", "UX"],
      companyName: "App Designers",
      contactInfo: "contact@appdesigners.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-18",
      applications: [
        { id: 60, name: "Hank", email: "hank@example.com" },
        { id: 61, name: "Ivy", email: "ivy@example.com" },
      ],
    },
    {
      id: 19,
      title: "Technical Writer",
      description: "Join us as a Technical Writer.",
      requirements: "Experience in writing technical documents.",
      tags: ["Technical Writing", "Documentation"],
      companyName: "TechDocs",
      contactInfo: "hr@techdocs.com",
      createdBy: "test456@gmail.com",
      createdAt: "2021-09-19",
      applications: [],
    },
    {
      id: 20,
      title: "Cloud Architect",
      description: "Seeking a Cloud Architect for our infrastructure.",
      requirements: "Experience with cloud technologies.",
      tags: ["Cloud", "Architecture", "Infrastructure"],
      companyName: "Cloud Architects",
      contactInfo: "info@cloudarchitects.com",
      createdBy: "test123@gmail.com",
      createdAt: "2021-09-20",
      applications: [
        { id: 65, name: "Mia", email: "mia@example.com" },
        { id: 66, name: "Nina", email: "nina@example.com" },
      ],
    },
  ];
  
  