export const postedJobs = [
    {
      id: 1,
      title: "Frontend Developer",
      description: "We are looking for a Frontend Developer to join our team.",
      requirements: "Proficiency in JavaScript, React, and CSS.",
      tags: ["JavaScript", "React", "CSS"],
      companyName: "Tech Innovations",
      contactInfo: "hr@techinnovations.com",
      applications: [
        { id: 1, name: "Alice", email: "alice@example.com" },
        { id: 2, name: "Bob", email: "bob@example.com" },
        { id: 3, name: "Charlie", email: "charlie@example.com" },
        { id: 4, name: "David", email: "david@example.com" },
        { id: 5, name: "Emma", email: "emma@example.com" },
        { id: 6, name: "Frank", email: "frank@example.com" },
        { id: 7, name: "Grace", email: "grace@example.com" },
        { id: 8, name: "Hank", email: "hank@example.com" },
        { id: 9, name: "Ivy", email: "ivy@example.com" },
        { id: 10, name: "Jack", email: "jack@example.com" },
      ],
    },
    {
      id: 2,
      title: "Backend Developer",
      description: "Seeking a Backend Developer for our services.",
      requirements: "Experience with Node.js and Express.",
      tags: ["Node.js", "Express", "MongoDB"],
      companyName: "Web Solutions",
      contactInfo: "hr@websolutions.com",
      applications: [
        { id: 11, name: "Liam", email: "liam@example.com" },
        { id: 12, name: "Mia", email: "mia@example.com" },
        { id: 13, name: "Nora", email: "nora@example.com" },
        { id: 14, name: "Oscar", email: "oscar@example.com" },
        { id: 15, name: "Paul", email: "paul@example.com" },
      ],
    },
    {
      id: 3,
      title: "UI/UX Designer",
      description: "Looking for a UI/UX Designer to enhance our user experience.",
      requirements: "Proficiency in Figma and Adobe XD.",
      tags: ["Design", "UI/UX", "Figma"],
      companyName: "Creative Minds",
      contactInfo: "design@creativeminds.com",
      applications: [
        { id: 16, name: "Quinn", email: "quinn@example.com" },
        { id: 17, name: "Rachel", email: "rachel@example.com" },
        { id: 18, name: "Steve", email: "steve@example.com" },
        { id: 19, name: "Tina", email: "tina@example.com" },
        { id: 20, name: "Uma", email: "uma@example.com" },
        { id: 21, name: "Victor", email: "victor@example.com" },
        { id: 22, name: "Wendy", email: "wendy@example.com" },
        { id: 23, name: "Xander", email: "xander@example.com" },
        { id: 24, name: "Yara", email: "yara@example.com" },
        { id: 25, name: "Zane", email: "zane@example.com" },
      ],
    },
    {
      id: 4,
      title: "DevOps Engineer",
      description: "Join our team as a DevOps Engineer.",
      requirements: "Experience with Docker, Kubernetes, and AWS.",
      tags: ["DevOps", "AWS", "Docker"],
      companyName: "Cloud Solutions",
      contactInfo: "hr@cloudsolutions.com",
      applications: [
        { id: 26, name: "Alice", email: "alice@example.com" },
        { id: 27, name: "Bob", email: "bob@example.com" },
        { id: 28, name: "Charlie", email: "charlie@example.com" },
        { id: 29, name: "David", email: "david@example.com" },
        { id: 30, name: "Emma", email: "emma@example.com" },
        { id: 31, name: "Frank", email: "frank@example.com" },
        { id: 32, name: "Grace", email: "grace@example.com" },
        { id: 33, name: "Hank", email: "hank@example.com" },
        { id: 34, name: "Ivy", email: "ivy@example.com" },
        { id: 35, name: "Jack", email: "jack@example.com" },
      ],
    },
    {
      id: 5,
      title: "Data Scientist",
      description: "We are looking for a Data Scientist to analyze data trends.",
      requirements: "Experience with Python, R, and Machine Learning.",
      tags: ["Data Science", "Python", "Machine Learning"],
      companyName: "Data Insights",
      contactInfo: "info@datainsights.com",
      applications: [
        { id: 36, name: "Kathy", email: "kathy@example.com" },
        { id: 37, name: "Liam", email: "liam@example.com" },
        { id: 38, name: "Mia", email: "mia@example.com" },
        { id: 39, name: "Nora", email: "nora@example.com" },
        { id: 40, name: "Oscar", email: "oscar@example.com" },
        { id: 41, name: "Paul", email: "paul@example.com" },
        { id: 42, name: "Quinn", email: "quinn@example.com" },
        { id: 43, name: "Rachel", email: "rachel@example.com" },
        { id: 44, name: "Steve", email: "steve@example.com" },
        { id: 45, name: "Tina", email: "tina@example.com" },
        { id: 46, name: "Grace", email: "grace@example.com" },
        { id: 47, name: "Hank", email: "hank@example.com" },
      ],
    },
    {
      id: 6,
      title: "Mobile App Developer",
      description: "Seeking a Mobile App Developer for our new project.",
      requirements: "Experience with Flutter and React Native.",
      tags: ["Mobile", "Flutter", "React Native"],
      companyName: "Tech Innovations",
      contactInfo: "careers@techinnovations.com",
      applications: [],
    },
    {
      id: 7,
      title: "System Administrator",
      description: "Looking for a System Administrator to manage our servers.",
      requirements: "Proficiency in Linux and network management.",
      tags: ["System Admin", "Linux", "Networking"],
      companyName: "Network Solutions",
      contactInfo: "admin@networksolutions.com",
      applications: [
        { id: 7, name: "Grace", email: "grace@example.com" },
        { id: 8, name: "Hank", email: "hank@example.com" },
      ],
    },
    {
      id: 8,
      title: "Project Manager",
      description: "Join us as a Project Manager to lead our projects.",
      requirements: "Experience with Agile methodologies.",
      tags: ["Project Management", "Agile", "Scrum"],
      companyName: "Project Leaders",
      contactInfo: "pm@projectleaders.com",
      applications: [],
    },
    {
      id: 9,
      title: "SEO Specialist",
      description: "Looking for an SEO Specialist to improve our web traffic.",
      requirements: "Experience with Google Analytics and SEO tools.",
      tags: ["SEO", "Digital Marketing", "Google Analytics"],
      companyName: "Marketing Pros",
      contactInfo: "hr@marketingpros.com",
      applications: [
        { id: 9, name: "Ivy", email: "ivy@example.com" },
      ],
    },
    {
      id: 10,
      title: "Content Writer",
      description: "Seeking a Content Writer to create engaging content.",
      requirements: "Excellent writing skills and creativity.",
      tags: ["Writing", "Content Marketing", "Blogging"],
      companyName: "Creative Content",
      contactInfo: "info@creativecontent.com",
      applications: [
        { id: 10, name: "Jack", email: "jack@example.com" },
      ],
    },
    {
      id: 11,
      title: "Network Engineer",
      description: "Join us as a Network Engineer to manage our networks.",
      requirements: "Proficiency in Cisco and network security.",
      tags: ["Networking", "Cisco", "Security"],
      companyName: "Tech Networks",
      contactInfo: "hr@technetworks.com",
      applications: [],
    },
    {
      id: 12,
      title: "Graphic Designer",
      description: "We are looking for a Graphic Designer to create visuals.",
      requirements: "Experience with Adobe Creative Suite.",
      tags: ["Design", "Graphics", "Adobe"],
      companyName: "Visual Arts",
      contactInfo: "hr@visualarts.com",
      applications: [
        { id: 11, name: "Liam", email: "liam@example.com" },
        { id: 12, name: "Mia", email: "mia@example.com" },
      ],
    },
    {
      id: 13,
      title: "Software Tester",
      description: "Seeking a Software Tester to ensure product quality.",
      requirements: "Experience with manual and automated testing.",
      tags: ["Testing", "QA", "Automation"],
      companyName: "Quality Assurance",
      contactInfo: "info@qualityassurance.com",
      applications: [],
    },
    {
      id: 14,
      title: "Sales Executive",
      description: "Looking for a Sales Executive to drive sales.",
      requirements: "Experience in B2B sales and negotiation.",
      tags: ["Sales", "B2B", "Negotiation"],
      companyName: "Sales Force",
      contactInfo: "hr@salesforce.com",
      applications: [],
    },
    {
      id: 15,
      title: "HR Manager",
      description: "We are looking for an HR Manager to lead our HR team.",
      requirements: "Experience in recruitment and employee relations.",
      tags: ["HR", "Recruitment", "Employee Relations"],
      companyName: "People First",
      contactInfo: "careers@peoplefirst.com",
      applications: [
        { id: 13, name: "Nora", email: "nora@example.com" },
      ],
    },
    {
      id: 16,
      title: "Business Analyst",
      description: "Join us as a Business Analyst to analyze market trends.",
      requirements: "Experience in data analysis and reporting.",
      tags: ["Business Analysis", "Data", "Reporting"],
      companyName: "Insight Analytics",
      contactInfo: "hr@insightanalytics.com",
      applications: [],
    },
    {
      id: 17,
      title: "Cybersecurity Analyst",
      description: "Looking for a Cybersecurity Analyst to protect our data.",
      requirements: "Experience with firewalls and intrusion detection.",
      tags: ["Cybersecurity", "Data Protection", "Firewalls"],
      companyName: "Secure Systems",
      contactInfo: "hr@securesystems.com",
      applications: [
        { id: 14, name: "Oscar", email: "oscar@example.com" },
      ],
    },
    {
      id: 18,
      title: "Cloud Engineer",
      description: "We are seeking a Cloud Engineer to manage cloud services.",
      requirements: "Experience with Azure and cloud architectures.",
      tags: ["Cloud", "Azure", "DevOps"],
      companyName: "Cloud Innovations",
      contactInfo: "info@cloudinnovations.com",
      applications: [],
    },
  ];
  